repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

# Optional hooks (uncomment to enable)
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.18.2
#   hooks:
#     - id: mypy
#       args: [--exclude, tests/]
#
# - repo: https://github.com/streetsidesoftware/cspell-cli
#   rev: v9.2.1
#   hooks:
#     - id: cspell # Spell check changed files
#     - id: cspell # Spell check the commit message
#       name: check commit message spelling
#       args:
#         - --no-must-find-files
#         - --no-progress
#         - --no-summary
#         - --files
#         - .git/COMMIT_EDITMSG
#       stages: [commit-msg]
#       always_run: true
