# Same as Black.
line-length = 88
indent-width = 4

# Support Python 3.10+.
target-version = "py310"

[lint]
select = [
    "A",  # prevent using keywords that clobber python builtins
    "B",  # bugbear: security warnings
    "E",  # pycodestyle
    "F",  # pyflakes
    "E4",
    "E7",
    "E9",
    "UP",  # alert you when better syntax is available in your python version
    "I",  # import order
    "D401",   # pydocstyle
    "RUF002",
    "SIM108",
    "FA100",
    "EM102",
    "D415",
#    "ANN202",
    #    "TRY003",
    #    "EM101",
#    "ALL",  # all rules
]
ignore = [
    "E712",  # Allow using if x == False, as it's not always equivalent to if x.
    "E501",  # Supress line-too-long warnings: trust black's judgement on this one.
    "FIX",
    "S101",
    "PLR2004",
    "TD",
    "D100",
    "PT011",
    "ANN001",
    "PLR0913",
    "SLF001",
    "D205",
    "D104",
    "FBT002",
    "FBT001",
    "PLC0206",
#    "PLR1714",
]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
docstring-code-format = true
# Set the line length limit used when formatting code snippets in
# docstrings.
docstring-code-line-length = "dynamic"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
