from pythermalcomfort.models import zhang_sensation_comfort
from pprint import pprint

dict_results = zhang_sensation_comfort(
    t_skin_local={
        "head": 34.3,
        "neck": 34.6,
        "chest": 34.1,
        "back": 34.3,
        "pelvis": 34.3,
        "left_shoulder": 33.2,
        "left_arm": 33.6,
        "left_hand": 33.4,
        "right_shoulder": 33.2,
        "right_arm": 33.6,
        "right_hand": 33.4,
        "left_thigh": 33.3,
        "left_leg": 31.8,
        "left_foot": 32.3,
        "right_thigh": 33.3,
        "right_leg": 31.8,
        "right_foot": 32.3,
    },
    t_skin_local_set={
        "head": 35.3,
        "neck": 35.6,
        "chest": 35.1,
        "back": 35.3,
        "pelvis": 35.3,
        "left_shoulder": 34.2,
        "left_arm": 34.6,
        "left_hand": 34.4,
        "right_shoulder": 34.2,
        "right_arm": 34.6,
        "right_hand": 34.4,
        "left_thigh": 34.3,
        "left_leg": 32.8,
        "left_foot": 33.3,
        "right_thigh": 34.3,
        "right_leg": 32.8,
        "right_foot": 33.3,
    },
    dt_skin_local_dt={
        "head": 0.01,
        "neck": 0.01,
        "chest": 0.01,
        "back": 0.01,
        "pelvis": 0.01,
        "left_shoulder": 0.01,
        "left_arm": 0.01,
        "left_hand": 0.01,
        "right_shoulder": 0.01,
        "right_arm": 0.01,
        "right_hand": 0.01,
        "left_thigh": 0.01,
        "left_leg": 0.01,
        "left_foot": 0.01,
        "right_thigh": 0.01,
        "right_leg": 0.01,
        "right_foot": 0.01,
    },
    dt_core_local_dt={
        "head": 0.01,
        "neck": 0.01,
        "chest": 0.01,
        "back": 0.01,
        "pelvis": 0.01,
        "left_shoulder": 0.01,
        "left_arm": 0.01,
        "left_hand": 0.01,
        "right_shoulder": 0.01,
        "right_arm": 0.01,
        "right_hand": 0.01,
        "left_thigh": 0.01,
        "left_leg": 0.01,
        "left_foot": 0.01,
        "right_thigh": 0.01,
        "right_leg": 0.01,
        "right_foot": 0.01,
    },
    options={
        "sensation_scale": "7-point",
    },
)

print(dict_results)
