name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
        - development

jobs:

  format:

    # check that the code is formatted correctly
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 🐍
      uses: actions/setup-python@v4
      with:
          python-version: '3.12'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install ruff
    - name: Lint
      run: ruff check ./pythermalcomfort ./tests
    - name: Check formatting
      run: ruff format --check ./pythermalcomfort ./tests

  test:
    needs: format

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.13' ]
        platform: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox and any other packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          python -m pip install "tox<4" tox-gh-actions
          python -m pip install ruff
      - name: Lint
        run: ruff check ./pythermalcomfort ./tests
      - name: Check formatting
        run: ruff format
      - name: Run Tox
        run: |
          tox
        env:
          PLATFORM: ${{ matrix.platform }}
